### ISSUE TITLE
CORS problem and latex formula displays with duplication

### ISSUE THREAD

**Issue by cheonson123** [lobehub/lobe-chat#4478] opened 2024-10-25 04:05 UTC
### 📦 部署环境

Docker

### 📌 软件版本

v1.22.19

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

I am using azure's gpt api on lobechat and it works well in most  cases.But when I ask the gpt to latex to display formulas,it will cause duplication, which seems to be caused by the failure of katex css to load correctly.The web development tool indicates a CORS problem at my lobechat (database version) web page. I have tried to add this  line' add_header 'Access-Control-Allow-Origin' '*' always' to my nginx conf.But it doesn't work.The prompt for CORS problem in the web development tool is as follows：
<img width="1012" alt="截屏2024-10-25 上午11 57 36" src="https://github.com/user-attachments/assets/c5b42e66-a1b8-4932-aac6-e8977e410870">
<img width="1020" alt="截屏2024-10-25 上午11 08 57" src="https://github.com/user-attachments/assets/6ad6fb31-acac-40cd-bc41-487c3e75be3a">
<img width="985" alt="截屏2024-10-25 上午11 11 39" src="https://github.com/user-attachments/assets/bb6a0602-45aa-46e8-aaa8-5277b0717020">
I have tried to use the same api to generate formula in latex on a different platform and it shows correctly with no duplication.So I think it's not the api's problem.
<img width="1241" alt="截屏2024-10-25 上午11 43 23" src="https://github.com/user-attachments/assets/b7bd04d3-38a1-429d-8ee8-de13eaa28a7b">

### 📷 复现步骤

Request GPT to reply formula using latex.

### 🚦 期望结果

Correctly display latex formula.

### 📝 补充信息

Since I didn't get an official nginx config for lobechat,I get one with GPT's help.I am not sure if nginx config causes these problems.Here's my nginx config：

location / {
    proxy_pass http://localhost:3210;

    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Credentials' 'true' always;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
    add_header Cache-Control no-cache;

    proxy_cache off;
    chunked_transfer_encoding on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 300;

  }

**Comment by arvinxx** [comment] 2024-10-25 04:18
I think you are using `.top` domain. duplicate of #4469

**Closed by arvinxx** 2024-10-25 04:18 UTC
Labels: 🐛 Bug
