### ISSUE TITLE
[Bug] Incomplete Chunk Recall

### ISSUE THREAD

**Issue by frankl02** [lobehub/lobe-chat#5082] opened 2024-12-19 06:56 UTC
### 📦 Environment

Official Preview

### 📌 Version

Newest

### 💻 Operating System

macOS

### 🌐 Browser

Edge

### 🐛 Bug Description

On the lobechat chatbot:

Whenever I upload a large file (ie chunked into many sections), the chatbot will only search through a limited portion of chunks. This always lead to missing information.

For example, when my files is 50 chunks, the bot only searches through 5 of them…

but the information I need is throughout the chunks.

I’m not a coder… and only want to use the lobechat bot conversation via the existing preview

How can we resolve this?

Many Thanks

**Comment by cy948** [comment] 2024-12-23 12:39
Current "search" implementation based on semantic similarity of query sentence and document chunks, those ways like describe more details on your questions, give more relevant examples and rewrite question into document language can boost the "search" performance.

**Comment by frankl02** [comment] 2024-12-23 22:50
Is it not possible for the bot to process the whole file, as opposed to only recalling 5 chunks? I know that the current recall limit is only 5 chunks. Are we gonna improve it? Make it the same as the normal 'attach file' function for official platforms(claud, chatgpt) ...

Thanks

**Comment by frankl02** [comment] 2024-12-23 22:52
I might have used the wrong word. I didn't mean to 'search' for a file. I want to attach the file into conversation and chat with the document. Currently, it seems that I could only do so by converting long documents into the prompt. Can we make 'attach file' function more practical and useful? Make it the same as the normal 'attach file' function for official platforms(claud, chatgpt) ...

**Comment by cy948** [comment] 2024-12-24 11:44
So you prefer inputting a whole attachment in the chat context?

**Comment by frankl02** [comment] 2024-12-24 11:47
Yes , if that's possible? Although it might cost more API, but it would allow more reliable document chat result.

Thanks

**Comment by arvinxx** [comment] 2024-12-25 05:42
duplicate of #4005. We will support it in the next iteration of knowledge base

**Closed by arvinxx** 2024-12-25 05:42 UTC
Labels: 🐛 Bug, files
