### ISSUE TITLE
[Bug] unable to use steam game reviews assistant with gemini-1.5-flash or gemini-1.5-pro

### ISSUE THREAD

**Issue by robbiered** [lobehub/lobe-chat#3466] opened 2024-08-13 22:29 UTC
### 📦 Environment

Docker

### 📌 Version

1.9.8

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

get this error when using steam game reviews assistant and plugin with gemini

`{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:streamGenerateContent?alt=sse: [400 Bad Request] * GenerateContentRequest.tools[0].function_declarations[3].parameters.properties: should be non-empty for OBJECT type\n* GenerateContentRequest.tools[0].function_declarations[4].parameters.properties: should be non-empty for OBJECT type\n"
  },
  "provider": "google"
}`

### 📷 Recurrence Steps

select steam game reviews assistant, try to use any text with gemini

### 🚦 Expected Behavior

expect it to respond without error

**Comment by RubuJam** [comment] 2024-08-14 05:25
This is a problem with Gemini. Its function calling capability is very poor. It is recommended to use models from other providers in conjunction with this plugin.

**Comment by arvinxx** [comment] 2024-08-22 16:23
duplicate of https://github.com/lobehub/lobe-chat/issues/2537

**Closed by arvinxx** 2024-08-22 16:23 UTC
Labels: 🐛 Bug
