### ISSUE TITLE
[Request] Use Azure OpenAI Services for DALL-E 3 Plugin

### ISSUE THREAD

**Issue by AnAn179** [lobehub/lobe-chat#3600] opened 2024-08-25 05:18 UTC
### 🥰 Feature Description

It supports the OpenAI API only, so how to use the Azure OpenAI?

### 🧐 Proposed Solution

Load config via env var?

**Comment by arvinxx** [comment] 2024-08-26 03:04
duplicate of #2536

**Closed by arvinxx** 2024-08-26 03:04 UTC
Labels: 🌠 Feature Request, dalle, azure
