### ISSUE TITLE
This branch is 18 commits behind

### ISSUE THREAD

**Issue by Root-FTW** [lobehub/lobe-chat#1695] opened 2024-03-22 17:39 UTC
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

My forked version no longer updates, why?
![image](https://github.com/lobehub/lobe-chat/assets/108767514/e5d98c07-8bb0-4092-bb1b-c996dd115c7c)

![screencapture-github-Root-FTW-lobe-chat-actions-runs-8394145006-2024-03-22-10_26_30](https://github.com/lobehub/lobe-chat/assets/108767514/bbd1e275-3d11-4ddc-b430-af0f3ef1f7d9)

**Comment by arvinxx** [comment] 2024-03-23 03:17
duplicate of #1696

**Closed by arvinxx** 2024-03-23 03:17 UTC
Labels: 🐛 Bug
