### ISSUE TITLE
v0.145.11版本不能azure-ad-SSO登录，同样变量在v0.145.6之前版本没有出现这个问题

### ISSUE THREAD

**Issue by linkiofo** [lobehub/lobe-chat#1891] opened 2024-04-03 17:18 UTC
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

v0.145.11版本不能azure-ad-SSO登录，同样变量在v0.145.6之前版本没有出现这个问题，点登录就提示500 Internal Server Error错误。
.
![屏幕截图 2024-04-04 010600](https://github.com/lobehub/lobe-chat/assets/156993166/bc737efd-dabd-4046-bec8-f3a5b6602f43)
![屏幕截图 2024-04-04 010310](https://github.com/lobehub/lobe-chat/assets/156993166/220f0b31-4fd7-4aac-8f25-7fadaaad354c)

**Comment by arvinxx** [comment] 2024-04-04 05:40
@EINDEX please help to check it?

**Comment by EINDEX** [comment] 2024-04-04 08:26
Hi @linkiofo,

Could you provide some information about your environment? I can't reproduce this in my environment.
Like the `SSO_PROVIDERS` value.

**Comment by EINDEX** [comment] 2024-04-04 08:30
Hi @arvinxx 

I found an issue point, the change below:

https://github.com/lobehub/lobe-chat/blame/edb10809c8b6438f6422aeb416c9f915fd927ba3/src/app/api/auth/sso-providers/azure-ad.ts#L8

is not the same as our document, in the document, we are using the `azure-ad`.

<img width="1031" alt="Screenshot 2024-04-04 at 16 27 36" src="https://github.com/lobehub/lobe-chat/assets/13883964/a442d784-3343-468c-8a41-5bf7d166a5bd">

So, the key of sso provider is changing form `azure-ad` to `azureAd`, Is it must to change to this style or we can change it back?

**Comment by EINDEX** [comment] 2024-04-04 08:50
I changed `SSO_PROVIDERS` `azure-ad` to `azureAd`, and the login process is successful.


Uploading Screen Recording 2024-04-04 at 16.41.20.mov…

**Comment by ykangw** [comment] 2024-04-04 10:11
I have the same issue. Azure AD worked in previous versions but has failed in the last two days. Environment variables including SSO variables are not changed.

**Comment by arvinxx** [comment] 2024-04-04 11:23
@EINDEX I think it's my mistake. Could you please change it back?

**Comment by EINDEX** [comment] 2024-04-04 11:40
@arvinxx I made this one-line change PR https://github.com/lobehub/lobe-chat/pull/1898 here. Please review.

**Comment by arvinxx** [comment] 2024-04-04 12:48
Fixed in 0.145.12

**Closed** 2024-04-04 12:48 UTC
Labels: 🐛 Bug
