### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sinxyz** [lobehub/lobe-chat#3329] opened 2024-07-26 13:24 UTC
### 📦 部署环境

Docker

### 📌 软件版本

v1.7.2

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

tools can't  work with ollama，but it can work with groq in same model

**Comment by arvinxx** [comment] 2024-07-26 14:18
https://github.com/lobehub/lobe-chat/pull/3327

**Comment by arvinxx** [comment] 2024-09-23 04:01
duplicate of #3436

**Closed by arvinxx** 2024-09-23 04:01 UTC
Labels: 🐛 Bug
