### ISSUE TITLE
[Request] elevenlabs.io Text To Speech API 

### ISSUE THREAD

**Issue by KnightNFS** [lobehub/lobe-chat#4059] opened 2024-09-21 15:40 UTC
### 🥰 Feature Description

To give users a wider choice of voices , can be use alternative Text-to-Speech service - elevenlabs.io API

### 🧐 Proposed Solution

Add new Speech Recognition Service selection "elevenlabs.io"
Add API key field ( and ENV VARIABLE )

**Comment by arvinxx** [comment] 2024-09-23 02:29
duplicate of #651

**Closed by arvinxx** 2024-09-23 02:29 UTC
Labels: 🌠 Feature Request, tts
