### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HaskyWang** [lobehub/lobe-chat#3309] opened 2024-07-25 09:35 UTC
### 📦 部署环境

Docker

### 📌 软件版本

1.6.11

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

**grop-api** 
前提：api key确认是正确的
1.不使用客户端请求模式 连通性检查报错 ，报错如下
![image](https://github.com/user-attachments/assets/9b731e75-2707-4904-9860-48ee117e7b08)
 Groq API Key 不正确或为空，请检查 Groq API Key 后重试
{
  "error": {
    "status": 401,
    "headers": {
      "alt-svc": "h3=\":443\"; ma=86400",
      "cf-cache-status": "DYNAMIC",
      "cf-ray": "8a8b2469defaada4-ATL",
      "connection": "keep-alive",
      "content-length": "306",
      "content-type": "application/json; charset=utf-8",
      "date": "Thu, 25 Jul 2024 09:32:21 GMT",
      "server": "cloudflare",
      "set-cookie": "__cf_bm=54w.Wlo1yR2Ip7emY5yJB5PCp9g7o0NPxDHifAOWvb8-1721899941-1.0.1.1-aWNdxQI.uO5iTBUy7xbo1FvIeiaBCP7ykAik_2fS98Y8X8KffY2pBuah579L3eej_F9GTuAikfzAxMQGbGl_RQ; path=/; expires=Thu, 25-Jul-24 10:02:21 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=sBc9jDrrkB0eGILulBzqqBI.bUlcru3_7dZNR8qj5w4-1721899941461-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None",
      "strict-transport-security": "max-age=15552000; includeSubDomains; preload",
      "vary": "Origin",
      "x-content-type-options": "nosniff",
      "x-request-id": "req_4921e167d56a18eeda8a9d8f20c4d489"
    },
    "request_id": "req_4921e167d56a18eeda8a9d8f20c4d489",
    "error": {
      "message": "Incorrect API key provided: gsk_4Epz********************************************DXnt. You can find your API key at https://platform.openai.com/account/api-keys.",
      "type": "invalid_request_error",
      "param": null,
      "code": "invalid_api_key"
    },
    "code": "invalid_api_key",
    "param": null,
    "type": "invalid_request_error"
  },
  "endpoint": "https://api.op****ai.com/v1",
  "provider": "groq"
}
2.使用客户端请求模式，并且客户端电脑开启代理，检查通过
![image](https://github.com/user-attachments/assets/ee5e1c99-78f2-44c1-b007-376e95d583c2)
所以可以确定api-key是没问题的

### 🚦 期望结果

检查出问题并修复

**Comment by ZachZimm** [comment] 2024-07-25 15:37
This seems to be a duplicate of Issue #3307 which should be fixed by pull request #3308

**Closed** 2024-07-26 11:11 UTC
Labels: 🐛 Bug
