### ISSUE TITLE
[Bug] docker-database depoly with S3 file stroge have trouble to load image into chat

### ISSUE THREAD

**Issue by Lostsite** [lobehub/lobe-chat#3843] opened 2024-09-09 05:01 UTC
### 📦 Environment

Docker

### 📌 Version

v1.15.18

### 💻 Operating System

Ubuntu, Other Linux

### 🌐 Browser

Firefox

### 🐛 Bug Description

When I upload image into chat, and hit run, the image (especially a large image) will take a few seconds to load it into the chat. At the same time, the llm model will NOT see the image, and cause error like "please provide image".

Wait a few seconds, until the image is fully loaded (able to see the full preview in chat), then rerun the conversation, and the llm would be able to correctly recognize the image.

### 📷 Recurrence Steps

Upload an image (>=1mb) to a chat (I upload to one of my chat bot) + ask the llm to describe the image, until the image is fully uploaded, hit send.

The image preview (in the chat) will show blank, and need a few seconds to show the preview of image. 

At the same time, llm will respond something like "please provide the image you want me to describe.

Wait a few seconds, until the image preview is fully loaded in side the conversation, rerun the llm, now it can correctly describe the image. 

### 🚦 Expected Behavior

I expected (a simple solution) is do NOT send anything through the api until the image is fully loaded. 

### 📝 Additional Information

Docker on Debian 12, with local pgsql installation.

**Comment by arvinxx** [comment] 2024-09-09 05:03
I think it's a bug. I will fix it soon

**Comment by Lostsite** [comment] 2024-09-09 05:34
- #3760

I think this is the same issue.

**Comment by arvinxx** [comment] 2024-09-10 14:30
@Lostsite yes

**Comment by arvinxx** [comment] 2024-09-10 14:30
duplicate of #3760

**Closed by arvinxx** 2024-09-10 14:30 UTC
Labels: 🐛 Bug
