### ISSUE TITLE
[Request] Added code preview plug-in

### ISSUE THREAD

**Issue by simon6668** [lobehub/lobe-chat#3364] opened 2024-07-30 05:39 UTC
### 🥰 Feature Description

Added code preview plug-in,Added code preview plug-in for easy code editing with claude3.5

### 🧐 Proposed Solution

Added code preview plug-in

**Comment by arvinxx** [comment] 2024-07-30 07:13
duplicate of #2981

**Closed by arvinxx** 2024-07-30 07:13 UTC
Labels: 🌠 Feature Request
